"""inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 14:00:16.377714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_id'), ['requester_id'], unique=False)

    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_creator_id'), ['creator_id'], unique=False)

    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semesters_user_id'), ['user_id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=1), nullable=False),
    sa.Column('min_pct', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_semester_id'), ['semester_id'], unique=False)

    op.create_table('no_class_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'date')
    )
    with op.batch_alter_table('no_class_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_no_class_days_semester_id'), ['semester_id'], unique=False)

    op.create_table('proposal_members',
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proposal_id', 'user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_semester_id'), ['semester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)

    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slots_course_id'), ['course_id'], unique=False)

    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', 'date')
    )
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absences_slot_id'), ['slot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absences_slot_id'))

    op.drop_table('absences')
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slots_course_id'))

    op.drop_table('slots')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_semester_id'))

    op.drop_table('events')
    op.drop_table('proposal_members')
    with op.batch_alter_table('no_class_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_no_class_days_semester_id'))

    op.drop_table('no_class_days')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_semester_id'))

    op.drop_table('courses')
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semesters_user_id'))

    op.drop_table('semesters')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposals_creator_id'))

    op.drop_table('proposals')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_id'))

    op.drop_table('friendships')
    op.drop_table('users')
    # ### end Alembic commands ###
