"""perfil

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 16:41:23.137130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=160), server_default='', nullable=False))
        batch_op.add_column(sa.Column('career', sa.String(length=60), server_default='', nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=60), server_default='', nullable=False))
        batch_op.add_column(sa.Column('banner_color', sa.String(length=7), server_default='#4f46e5', nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('avatar_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar_version', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('username_changed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('display_name_changed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('display_name_changed_at')
        batch_op.drop_column('username_changed_at')
        batch_op.drop_column('avatar_version')
        batch_op.drop_column('avatar_type')
        batch_op.drop_column('avatar')
        batch_op.drop_column('banner_color')
        batch_op.drop_column('status')
        batch_op.drop_column('year')
        batch_op.drop_column('career')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
